### ISSUE TITLE
Why not use a templating engine?

### ISSUE THREAD

**Issue by fabianegli** [openZH/startercode-generator_openZH#2]
Was it a conscious decision to not use Jinja2 for the template compilation? This would make the code more descriptive and easier to work with.

**Comment by rnckp** [comment]
@fabianegli Thanks for the suggestion!

At the time not using any templating framework seemed the right approach to quickly whip up the prototype. 

I am not entirely convinced that using an engine would make adaptation of the starter code that much easier. A user would need to be familiar with Jinja or other engines. So I kept it as simple as possible.

In addition I am not sure if this would work for the notebook file format. To inject the code for the data set import I need to load the template as JSON (code line 151). Not sure if this would work with an engine. 

But again, thanks for asking and the suggestion. 

Cheers, Patrick
